### ISSUE TITLE
Age and Sex of Survival Estimates?

### ISSUE THREAD

**Issue by Huh** [Huh/PopR_Jasper#1]
@annam21 

The Sex and Age of the survival estimates is NA/blank.  We should assign these a sex and age unless they are meant to be used for ages and sexes.

**Comment by annam21** [comment]
@Huh That shouldn't be the case in IPM_DB_0.2.RData. The difference between the two databases is the survival estimates. In database 1, I put in the survival estimates they gave me (which I believe should all be for adult females, if a person wanted to add that info). In Database 2, I ran the known fate model and saved the survival estimates for adult females.

**Comment by annam21** [comment]
@Huh Database2 should also have survival estimates for more years because the data were more up-to-date.

**Comment by Huh** [comment]
Fixed by changing to ipm_db_0.2 in commit https://github.com/SpeedGoat/Alberta/pull/22/commits/b314cdd10f39e30c51a7ac05da8517ad7cacf5c3
