### ISSUE TITLE
Consider adding juveniles to tranlocation table

### ISSUE THREAD

**Issue by Huh** [Huh/PopR_Jasper#10]
Currently we can only add adults to the future populations.  We will want the ability to add juveniles to the population.  They requested to add animals 15 months of age and older.

**Comment by annam21** [comment]
They want to translocate only animals that are 15 months

**Comment by Huh** [comment]
Added in https://github.com/SpeedGoat/Alberta/commit/898a3b389d672485941ab901e4ce7fda0b26bce9

We can also add all other age classes if desired.  For the moment we restrict to J for pretty presentation.
