### ISSUE TITLE
Just one DAU?

### ISSUE THREAD

**Issue by Huh** [Huh/PopR_Jasper#2]
@annam21

We have data for multiple DAUs, but we are only using one?

**Comment by Huh** [comment]
If we need functionality for more than one

- [ ] add other DAUs to dics

**Comment by annam21** [comment]
That's right. We all decided to only do the analysis on Tonquin, since the others had so little data (and are basically extinct).

**Comment by Huh** [comment]
Nice, thanks!  Do you want to present the data from the other units?

**Comment by annam21** [comment]
@Huh I guess we could. Slash maybe should? But then will that lead to more questions about why we didn't report those results as well? I'm torn. It seems like the right thing to do from their perspective but it also seems like it would open a giant can of worms about wrong models/strong priors/lack of data. So.... up to you?

**Comment by Huh** [comment]
Sticking with one DAU for now.  The data from the other units are available, but the website will throw an error if an attempt to run models for those units is made.
